version: '3.8'

services:
 
  api-gateway:
    container_name: api-gateway
    build:
      context: ./src/Gateway/ApiGateway
      dockerfile: Dockerfile
    ports:
      - "7000:8080"
    depends_on:
      - kullanici-servisi
      - urun-servisi
      - siparis-servisi 
    networks:          
      - ecom_network
  
  web-bff:
    container_name: web-bff
    build:
      context: ./src/BFF/WebBff.API
      dockerfile: Dockerfile
    ports:
      - "5003:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:         
      - ecom_network
    

  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kullanici_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:          
      - ecom_network

  rabbitmq:
    image: rabbitmq:3.11-management 
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672" 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest 
    networks:
      - ecom_network 

      
  kullanici-servisi:
    container_name: kullanici-servisi
    build:
      context: ./src/Services/Kullanici.API
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=kullanici_db;Username=user;Password=password
    depends_on:
      - postgres-db
    networks:          
      - ecom_network

  urun-servisi:
    container_name: urun-servisi
    build:
      context: ./src/Services/Urun.API
      dockerfile: Dockerfile
    ports:
      - "5002:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=urun_db;Username=user;Password=password 
    depends_on:
      - postgres-db
    networks:          
      - ecom_network

  siparis-servisi:
    container_name: siparis-servisi
    build:
      context: .
      dockerfile: src/Services/Siparis.API/Dockerfile
    ports:
      - "5004:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=siparis_db;Username=user;Password=password
      - RabbitMQ__Host=rabbitmq 
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - postgres-db 
      - rabbitmq
    networks:          
      - ecom_network


  notifikasyon-servisi:
    container_name: notifikasyon-servisi
    build:
      context: .
      dockerfile: src/Workers/Notifikasyon.Worker/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - rabbitmq
    networks:
      - ecom_network


volumes:
  pgdata:
  rabbitmq_data:  
  
networks:
  ecom_network:
    driver: bridge