// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Siparis.API.Data;

#nullable disable

namespace Siparis.API.Data.Migrations.SagaDb
{
    [DbContext(typeof(SagaContext))]
    [Migration("20250731132059_siparisKalemiAddSaga")]
    partial class siparisKalemiAddSaga
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Siparis.API.Sagas.SiparisSagaState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SiparisId")
                        .HasColumnType("integer");

                    b.Property<string>("SiparisKalemleri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ToplamTutar")
                        .HasColumnType("double precision");

                    b.HasKey("CorrelationId");

                    b.ToTable("SagaStates");
                });
#pragma warning restore 612, 618
        }
    }
}
